chandrikadeb7/Hacktoberfest_2021

Task 3/RSA Algorithm
RSA Algorithm 128 bit  Using C++
=>  RSA Algorithm

Task 1/Weekly Sales/Question.md, Task 1/Weekly Sales/Solution.py
I added a simple python question and solution to the respected task 1 folder.
=> Added a Question to Task 1

Task 1/Forming A Magic Square/Question.md, Task 1/Forming A Magic Square/Solution.cpp, Task 1/Viral Advertising/Question.md, Task 1/Viral Advertising/Solution.cpp
Thank you so much for offering this opportunity. These both these questions are available on HackerRank.
=> Added Viral Advertising and Forming A Magic Square

Task 1/COVID19B/Question.md, Task 1/COVID19B/Solution.cpp, Task 1/PerfectPeak/Question.md, Task 1/PerfectPeak/Solution.cpp
First Program is about checking if there is a perfect peak in an array.
Second Program is from Codechef September Long Challenge.
=> Task 1 CP problems

Task 1/Minimum Vertex Cover/Question.md, Task 1/Minimum Vertex Cover/Solution.cpp
Added the minimum vertex cover problem for binary trees. Please Review...
=> Added Vertex Cover Problem

README.md
the readme contains a documented directory structure. There the text between the `<` and `>` is hidden in the rendered output. 
Thought the layout looks better with a real ascii tree layout.
=> layout of directories improved

Task 1/LongestArithmeticSubsequence/answer.cpp, Task 1/LongestArithmeticSubsequence/question.md
=> longest arithmetic subsequence

Task 1/Missing a Point/PTMSSNG.cpp, Task 1/Missing a Point/Question.md
Added Task 1 Missing a point problem. Please review it. @chandrikadeb7
=> Added Task 1 Missing a point problem

Task 3/Luhn Algorithm/LuhnValidator.java
Here is an implementation of Luhn Algorithm using Java.
=> Luhn Algorithm implemented with Java

Task 1/CHEFWED/question.md, Task 1/CHEFWED/solution_chefwed.cpp
A great question of dynamic programming that I found interesting as well as challenging while solving. Give it a view and merge if you think it to be good.
=> Added CHEFWED question and its solution

Task 3/Compression_Decompression_Algorithms/Compression/Compression.kt, Task 3/Compression_Decompression_Algorithms/Decompression/Decompression.kt
Compression Decompression Algorithms Using Kotlin
=> Compression & Decompression Algorithms Using Kotlin

README.md
Hello @chandrikadeb7,
I made a few changes to the README.md file to reflect the change that GitHub had made recently with the renaming of the default repository from master to main.
=> Update on the README.md file to change the repo name from master to main

Task 1/Alphabet Rangoli/Question.md, Task 1/Alphabet Rangoli/Solution.py
Submitting PR request for a problem from Hackerrank.
=> Solution to the Alphabet Rangoli from Hackerrank

Task 3/Binary Search Algorithm/BinarySearch.java, Task 3/Merge Sort Algorithm/MergeSort.java
=> add Binary search and Merge algos in java

Task 1/Comparison_in_js/example.js, Task 1/Comparison_in_js/question.md
I have made the above addition in TASK 1
=> js ques and soln added

Task 3/Dijkstra Algorithm/Dijkstra.cpp
**Dijkstra Algorithms**- a _single source shortest path_ algorithm.
=> Implementation of Dijkstra Algorithm in C++17 using priority queue

Task 1/Tower-of-Hanoi/Tower-of-hanoi.md, Task 1/Tower-of-Hanoi/TowerOfHanoi.java
A mathematical problem of tower of hanoi is added with algorithms in comments of code
=> Tower of Hanoi 

Task 1/Longest Increasing Subsequence/Question.md, Task 1/Longest Increasing Subsequence/solution.cpp
Added the question and solution to the problem.
=> Leetcode Problem - Longest Increasing Subsequence 

Task 3/QuickSort/Randomized_quicksort.c, Task 3/QuickSort/quicksort.c
added both the files and remove question.md
=> new pull req

Task 1/caesar cipher/question.md, Task 1/caesar cipher/solution.py
added question.md and solution.py in task 1 folder. 
@chandrikadeb7 please consider this PR for hacktoberfest 2020
=> task 1/caesar cipher

Task 1/STRNO/Question.md, Task 1/STRNO/Solution.cpp, Task 1/Time conversion/Question.md
Added a question called Strange Number along with solution in Task 1
=> Added a number theory question with solution in Task 1

Task 1/GenericLinkedList/Question.md, Task 1/GenericLinkedList/Solution.c, Task 1/Time conversion/Question.md
Unlike C++ and Java, C doesn’t support generics. So, how do we create a linked list in C that can be used for any data type? In C, we can use a void pointer and function pointer to implement the same functionality. One great thing about void pointer is that it can be used to point to any data type. Also, size of all types of pointers is always is same, so we can always allocate a linked list node. Function pointer is needed process actual content stored at address pointed by void pointer. 
A sample C code to demonstrate working of generic linked list will help you accomplish this task.
=> Generic linked list in c

Task 1/Booths_Algo/Question.md, Task 1/Booths_Algo/Solution.c
I have added the solution to Booth's algorithm used for the multiplication of binary numbers. It multiplies
- +ve to +ve
- +ve to -ve
- -ve to -ve 
binary equivalents of decimal numbers.
=> Completed Task 1 and added file Booths_Algo Question and Solution

Task 1/Permutations_and_Combinations/P&C.c, Task 1/Permutations_and_Combinations/Questions.md
For Open Source Beginners a little basic idea about Permutations and Combinations in C. Thank you for making this repository so easily understandable, hoping that you will merge this PR in your Repository.
=> C program of Permutations and Combinations

Task 3/sieve-of-eratosthenes/sieve-of-eratosthenes.cpp
=> sieve-of-eratosthenes algorithm

Task 1/CVDRUN(codechef)/question.md, Task 1/CVDRUN(codechef)/solution.cpp
https://www.codechef.com/OCT20B/problems/CVDRUN/
this is the link to that Question.
=> Added a CP question from codechef

Task 1/Million Dollars/Question.md, Task 1/Million Dollars/Solution.c
I added a simple C Program question and the solution to the respective task 1 folder
=> Added a Question and Solution to Task 1

Task 1/Element Appearing More Than 25% In Sorted Array/question.md, Task 1/Element Appearing More Than 25% In Sorted Array/solution.cpp, Task 1/Product of Array Except Self/question.md, Task 1/Product of Array Except Self/solution.cpp
Element Appearing More Than 25% In Sorted Array
=> Question updated in Task 1 

Task 3/activityselectionproblem/activityselection.cpp
activity selection using greedy method . @chandrikadeb7  please verify
=> activityselection.cpp

Task 1/Barrels (CodeForces)/Question.md, Task 1/Barrels (CodeForces)/Solution.js, Task 1/Number of Apartments (CodeForces)/Question.md, Task 1/Number of Apartments (CodeForces)/Solution.js, Task 1/Numbers on WhiteBoard (CodeForces)/Question.md, Task 1/Numbers on WhiteBoard (CodeForces)/Solution.js, Task 1/String Deletion (CodeForces)/Question.md, Task 1/String Deletion (CodeForces)/Solution.js, Task 1/String Reversal (CodeForces)/Question.md, Task 1/String Reversal (CodeForces)/Solution.cpp
Solutions of Educational Codeforces Round 96 (Rated for Div. 2) :
* A (JavaScript)
* B (JavaScript)
* C (JavaScript)
* D (JavaScript)
* E  (C++)
=> Educational Codeforces Round 96 (Rated for Div. 2)

Task 3/Minimum-Spanning-Tree/kruskal.cpp
This program shows the implementation of Kruskal's Algorithm which shows the minimum spanning tree cost of the input graph
Here it is implemented using Disjoint set data structure .
=> Implementation of Kruskal's Algorithm.

Task 3/DoublyLinkedList/DoublyLinkedList.cpp
Implemented a doubly linked list in CPP.
A node can be inserted and deleted. The program runs until the user want and can add/remove as many nodes as the user wants, until, ofcourse, stackoverflow.
=> Doubly Linked List program in cpp

Task 1/1D Array Duplicate Deletion O(n) time, O(1) Space/Question.md, Task 1/1D Array Duplicate Deletion O(n) time, O(1) Space/removeDuplicatesSorted.java
The function removeDuplicates takes a sorted array nums. If the excluding the duplicates, there are 'n' elements in nums, this function brings them to first n indices, in O(n) time, with in-place array operations (O(1) Space Complexity). The idea is using two pointers. The function, then returns n. Since re-arrangement has been done, the main function can now access n first elements of any user submitted array, so that all n elements are the unique elements of that array.
Eg : Enter number of elements: 8
Enter elements separated by space: 1 1 2 2 2 3 3 4
Array without the duplicate is: 1 2 3 4
=> Remove Duplicates in a Sorted Array

Task 1/FormatStringOfNames/Question.md, Task 1/FormatStringOfNames/Solution.js
Given: an array containing hashes of names
Return: a string formatted as a list of names separated by commas except for the last two names, which should be separated by an ampersand.
=> FormatStringOfNames

Task 1/Cats and a Mouse(Hackerrank)/problem.md, Task 1/Cats and a Mouse(Hackerrank)/solution.py
A problem "Cats and a Mouse" added to Task 1 .
The problem is solved in python language.
=> Added a problem from Hackerrank

Task 1/Zero Matrix/Question.md, Task 1/Zero Matrix/ZeroMatrix.java
Added one problem in task1 with the solution.
=> added zeroMatrix problem from the book "cracking the coding interview".

Task 1/SortColors/Question.md, Task 1/SortColors/SortColors.java
Added question : Leetcode 75.Sort Colors and solution to it
=> Task 1 added question, solution 

Task 3/Stack/Reverse_stack.java
This is a java program that aims at getting the output of a stack in reverse ie. in the bottom to up format rather than up to bottom. This is basically a FIFO kind of implementation of a stack using a temporary stack.
=> Reverse stack output

Task 1/ADAMAT(Codechef)/question.md, Task 1/ADAMAT(Codechef)/solution.cpp, Task 3/Minimum-Spanning-Tree/kruskal.cpp
Now I have created Solution file for the problem.
=> Created new folder in Task 1

Task 1/ginortS (Hackerrank)/ginortS.md, Task 1/ginortS (Hackerrank)/ginorts.py
Added a python script containing the solution as well as readme file containing the problem description with sample input and output.
=> solution to ginortS from Hackerrank

Task 1/Game_of_Two_Stacks/question.md, Task 1/Game_of_Two_Stacks/solution.cpp
Hello
I have added a new folder in task-1 regarding the game of two stacks which consists of questions and their solutions. I hope to be approved to be able to contribute to your repository
thank you!
=> Added question and solution for game of two stacks in cpp

Task 1/FindTheLeader(Prepbytes)/question.md, Task 1/FindTheLeader(Prepbytes)/solution.java
Just wanted to contribute to your repository with one of my favourite array question from PrepBytes. I hope this helps, this is my first contribution to open source. Thank you so much
=> Prepbytes Array Question

Task 1/Krishnamurthy Number/Krishnamurthy_number.cpp, Task 1/Krishnamurthy Number/readme.md
Added the Effiecient and Easiest way to check whether a number is Krishnamurhty Number
=> Added Krishnamurthy Number Algorithm

Task 1/Intersection_of_sorted_linkedlists/Intersection_of_sorted_linkedlists.cpp, Task 1/Intersection_of_sorted_linkedlists/question.md
I have added the "Intersection of Sorted Linked Lists" problem and solved it in CPP.
=> added intersection_of_sorted_linkedlists program in CPP

Task 1/Trapping Rain Water Problem/Question.md, Task 1/Trapping Rain Water Problem/TrappingRain.java
Trapping Rain Water Problem Solution in Java
HAcktoberFest_2020
=> Contributing Leetcode Problem Solution

README.md
=> Addition of max=300 param for contributors image

README.md
Hello @chandrikadeb7 Let me know if there is any change needed in the documentation. 
Also, I enjoyed this doing for the first time ever and it got me happy too, so thank you for the amazing beginner friendly issues! 😀
=> Updated information related to Hacktoberfest

Task 1/Trapping Rain Water Problem C++/Question.md, Task 1/Trapping Rain Water Problem C++/Trapping Rain Water.cpp
I am a participant of **Hacktoberfest 2021**. Kindly review and merge this branch or please label it as 'hacktoberfest-accepted' . Thank You !!
**Question :** Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
**Solution :** The solution is in C++ language.
=> Added Trapping Rain Water Problem C++ Folder in Task 1 

Task 1/BalancedBracketProblem/problem.md, Task 1/BalancedBracketProblem/solution.py
Added solution to the problem of Balanced Brackets, which is implemented using stack in Python language. The code is simple and well-commented.
=> A solution to balanced bracket problem

Task 1/Converting Roman Numerals to Decimal lying between 1 to 3999/question.md, Task 1/Converting Roman Numerals to Decimal lying between 1 to 3999/solution.cpp
Add a problem to convert roman numeral to decimal and its c++ solution
=> add problem to Convert Roman numeral to Decimal

Task 1/Longest Common Prefix/question.md, Task 1/Longest Common Prefix/solution.cpp
Added the problem "Longest Common Prefix"
=> Add longest common prefix

Task 1/Reverse a string using stack/question.md, Task 1/Reverse a string using stack/solution.cpp
Added the problem "reverse a string using stack".
=> Add reverse a string using stack

Task 1/Detect loop in a linked list/question.md, Task 1/Detect loop in a linked list/solution.cpp
Added the problem "Detect a Loop in a Linked List"
=> Add Detect a Loop in a Linked List

Task 1/alphabet position/alphabet_position.c, Task 1/alphabet position/question.md
I solved a problem using c language.
=> task 1 solved
